### ISSUE TITLE
Vue component tags having a different color than native HTML tags

### ISSUE THREAD

**Issue by wishinghand** [vuejs/vue-syntax-highlight#102]
Is there any merit to coloring custom components slightly differently than normal HTML tags? For instance if I had a component of `<example-component></example-component>` it would have a different color than `<div></div>`.

I see this as useful the more I run into components with lots of markup (like the div-itis that Bootstrap can cause).

**Comment by yyx990803** [comment]
Maybe - but an alternative is using PascalCase for your components (this is fully supported in Vue files as long as you register the components with PascalCase as well):

``` html
<div>
  <ExampleComponent/>
</div>
```

**Comment by wishinghand** [comment]
The codecase I'm working in actually does that, but it can still be a little tricky to find things. Only on complicated markup like custom navbars. Usually the components are smaller and it's not as big a deal.

**Comment by skyronic** [comment]
Thank you for taking the time to suggest this. Unfortunately I don't know if it's feasible to do this since we're largely using the native sublime HTML implementation and it's not straight forward to distinguish between a HTML tag and tag for custom component.

Please feel free to open a new issue if there's any other suggestions you have for things we can implement.
