### ISSUE TITLE
Emmet completions not working in <style lang="stylus"></style>

### ISSUE THREAD

**Issue by etune** [vuejs/vue-syntax-highlight#149]
I'm using Sublime Text on Windows.

```CSS
<style lang="stylus">
  body
    p10  <-- pressing TAB here doesn't work
</style>
```
Completions do work in standalone stylus files, just not in single file components. The completions also work with other lang attributes (less, sass, etc).

I've removed and re-added the Sublime Stylus Package.
https://github.com/billymoon/Stylus

**Comment by skyronic** [comment]
This is strange. I checked and abbrevations like `p!+m10e!` work fine but `p10` doesn't. Also it seems to work with other languages.

I suspect this might be a problem with the emmet package, and it's tab handling. Can you report there, and mention that we're using an **embedded scope**, since that might be a cause of the issue. But I can't figure out why this is happening and if it's an issue with the syntax highlight package.

**Comment by etune** [comment]
Looks like this issue has already been reported with the emmet package...

sergeche/emmet-sublime#657

**Comment by skyronic** [comment]
Marking as closed since this is an issue with emmet and not vue-syntax-highlight.

**Comment by linkhanfeng** [comment]
Emmet.subliem-settings

"syntaxProfiles": {
    "vue": "html"
  }
This is working for me!
