### ISSUE TITLE
pre-announcement of changes to LESS syntax

### ISSUE THREAD

**Issue by braver** [vuejs/vue-syntax-highlight#169]
A few months ago a new version of LESS was released that changed the root selector to `source.css.less`. The intention at the time was to bring the syntax in line with CSS, and thereby make more extensions like autocompletion and key bindings work for both out of the box. It got us 95% of the way there, but the recursion in LESS (and SCSS for that matter) makes it impossible to get there completely. In essence, the CSS syntax, and therefore its autocomplete features, leans heavily on the fact that properties and selectors are each in their own neatly delineated spaces. This doesn't always work for LESS, and the way extensions are inherited doesn't leave us another option than making a clean break. 

So, I intend to release LESS 2.5 soon. It has important improvements that are only possible by moving a few steps away from the way the CSS package does things. It will also revert the root scope back to `source.less`. I would like to coordinate this release so that Vue users don't experience breakage again (sorry about last time!). If all goes well no-one has to notice anything. Perhaps we can pick a time and date to make the change?

**Comment by LinusBorg** [comment]
Hey @braver,

thank you very much for reaching out proactively, highly appreachiated.

I'm currently trying to find the best team member to discuss this with you (I'm not hte one for use) - can you give me a bit more info, since I don't clearly understand the scope of the change you are talking about: 

* is this about Less *syntax* getting a breaking change for people writing LESS?
* Or is it about changes specifically related to syntax highlighting of LESS code, but authors writing LESS markup won't be affected?
* Since this repo is about the sublim syntax highlighting specifically: is ithis only about sublime, or something more general?

Apologies for asking potentially stupid questions, just wanna wrap my head around the scope of this challenge so I know who to involve.

**Comment by braver** [comment]
@LinusBorg Hi, the vue syntax imports the LESS syntax via its scope. Basically what needs to be done is revert this commit: https://github.com/vuejs/vue-syntax-highlight/commit/2e8c5b938264b482bb9eb177171dd82701faebff

**Comment by LinusBorg** [comment]
Thanks, got it.

**Comment by skyronic** [comment]
Hi @braver that sounds good. Thank you for letting us know. Can you email me at skyronic@gmail.com to schedule a time to make the switch?

**Comment by braver** [comment]
@skyronic I just tagged LESS 2.5.0 with the proposed changes.

**Comment by braver** [comment]
> I still don't have LESS 2.5.0 in my package list

package control can need over an hour to catch the updates, I'll keep an eye on it.

**Comment by skyronic** [comment]
Looks like everything is working well. Please feel free to re-open if any action is required. 

![image](https://user-images.githubusercontent.com/80173/48806394-2d37ce80-ece8-11e8-9c71-145d87bfc632.png)
