### ISSUE TITLE
how about webstorm support?

### ISSUE THREAD

**Issue by zhongqf** [vuejs/vue-syntax-highlight#3]

**Comment by yyx990803** [comment]
I personally never use webstorm, feel free to contribute...

**Comment by richarddewit** [comment]
+1

**Comment by cmosguy** [comment]
+1

**Comment by yyx990803** [comment]
You should be able to use this with WebStorm's [import TextMate Bundle functionality](https://www.jetbrains.com/phpstorm/help/textmate-bundles.html), since the main file is a `.tmLanguage` file.

**Comment by weilao** [comment]
In webstorm, this works fine for me:
Open `Settings` => `File Types` find `HTML` in `Recognized File Types`, then add `*.vue` as a new `Registered Patterns`.

**Comment by jlem** [comment]
I use PHPStorm, and while this works, it doesn't recognize ES6 syntax so it throw faux syntax warnings :/

**Comment by ifyio** [comment]
This works in webstorm

```js
<script type="text/babel">
     // your code here...
</script>
```

Just make sure to add `*.vue` to the `HTML` file type as described by @weilao

**Comment by duebbert** [comment]
@ifyio Any idea how to enable something similar for the style, so that <style lang="sass" type="text/scss"> is shown correctly in Webstorm?

**Comment by mmieluch** [comment]
@duebbert Open `Settings` => `Editor` => `Language Injections` and create a new injection of type `XML Attribute Injection` using the following parameters:

Name: `SCSS`
ID: `SCSS (SCSS files)` (SASS plugin has to be enabled, otherwise it's not gonna be listed)
Local name: `style`
XPath condition: `lower-case(@lang)='sass'`

Worked for me.

**Comment by duebbert** [comment]
@mmieluch Thanks, but unfortunately this didn't work for me (using PyCharm which might be the reason)

**Comment by dcorb** [comment]
Thanks @ifyio . It worked
![image](https://cloud.githubusercontent.com/assets/881333/11315163/82ee637e-8fe5-11e5-9226-a3dd6a6d093d.png)

**Comment by textbookcharlie** [comment]
@mmieluch This didn't work for me either. I played a round with the XML Attribute Language injections quite a bit, trying to get them to work. This is the only thing keeping from from switching to vueify :(

Any chance you could export the Language Injection entry you made and share it with us? Maybe we're doing something wrong.

**Comment by mmieluch** [comment]
@textbookcharlie Yea, I got all excited and posted here immediately, but now it's not working for me either. I use PhpStorm EAP versions and at that time I was playing around with other highlighting packages. Now I have a new version of the IDE and I haven't the slightest idea how to set it up again. Sorry to disappoint, but I'm as stuck as you guys... I'll edit my previous comment and strike out the solution as a no-go.

**Comment by mmieluch** [comment]
There's a feature request for inline LESS/SASS support in JetBrains bugtracker:

https://youtrack.jetbrains.com/issue/WEB-14762

I suppose upvotes are quite welcome :)

**Comment by noleafclover614** [comment]
@dcorb Does it work for you when you use the ```@click``` shorthand for ```v-on:click``` ?

**Comment by menghuan758** [comment]
Thanks. It worked

**Comment by dcorb** [comment]
Please upvote this one:
https://youtrack.jetbrains.com/issue/WEB-19082

I downloaded latest PHPstorm 10.0.3, still the previous screenshot I did with ````v-on-click ```` in red is the same. Nothing has changed. Has anyone tried PHPstorm 11 EAP ?

@mmieluch in this issue said that the LESS/SASS support feature request, quoting:  "are planning to fix in the next release cycle" 

@noleafclover614  
````@click```` syntax in the screenshot doesn't show like an error. 

![image](https://cloud.githubusercontent.com/assets/881333/12535878/3c82fc42-c28a-11e5-8e69-0e7bccd39c14.png)

**Comment by BelinChung** [comment]
Vue syntax highlight for IDEA: https://github.com/henjue/vue-for-idea

**Comment by zolotov** [comment]
Hi all,

In the next PhpStorm/Webstorm EAP it will be possible to inject sass/scss/less/stylus languages in style tag using `rel` attribute. E.g.:

```html
<style rel="stylesheet/less">
  @var: red;
  div { color: @var }
</style>
<style rel="stylesheet/scss">
  $var: red;
  div { color: $var }
</style>
```

Is this ok for you or something else is needed for style tag? Just in case, the question is only about stylesheet-part, I have nothing to do with html and js parts.

**Comment by mmieluch** [comment]
@zolotov Well, we could always do something like

```html
<style lang="less" rel="stylesheet/less">
  @var: red;
  div { color: @var }
</style>

<style lang="sass" rel="stylesheet/scss">
$var: red;
div { color: $var }
</style>
```

I personally would have absolutely no problem with additional attribute, since I use live templates/snippets for blocks like those anyway.

So yea, for me sounds great, nice one! :+1:

**Comment by zolotov** [comment]
@mmieluch Thanks for reply. I didn't know about `lang` attribute and its possible values in vuejs. Could you point me where I can read about it please? 

`rel` attribute is used because of documentation at http://lesscss.org/#using-less. If vuejs uses `lang` attribute I can support it as well, but I need any doc about this and also I should know which attribute is more important, e.g. what language should be injected in case of:

```html
<style lang="sass" rel="stylesheet/less">
</style>
```

**Comment by piotros** [comment]
@zolotov you can read about `lang` attribute in the official vue-loader documentation: http://vuejs.github.io/vue-loader/configurations/pre-processors.html

In Vue components `rel` attribute hasn't got any special meaning so it would be great to have support based only on `lang` attribute.

**Comment by mmieluch** [comment]
@zolotov Sure, mate. So Vue allows to create components in a single file, like so: http://vuejs.org/guide/application.html#Single_File_Components Then, single file components are being transformed using `vue-loader`: http://vuejs.github.io/vue-loader/configurations/pre-processors.html

In your example, `vue-loader` would transform it as a SASS file, but WebStorm would apply formatting for Less.

However, looking at the semantics of both `rel` and `lang` attributes, I believe `lang` is a far better option. As far as I'm aware `style` tag does not even have a `rel` attribute in the specification, but it does have `lang`, as a global one: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang And, if you look again at the Less documentation you linked, you can see they use it not in a local context of a `style` tag, but in a `link`, which makes sense in that case, but not when you define your Less/SASS/whatever locally, in-file. Please feel free to correct me if I'm wrong.

It would be nice to get some more input from other community members interested in this.

**Comment by zolotov** [comment]
@mmieluch @piotros Thanks for the links, will investigate. 

As for attributes, `rel` is presented in [spec](https://www.w3.org/TR/html401/struct/links.html#adef-rel) of (`style tag`](https://www.w3.org/TR/html401/present/styles.html). However [`lang` attribute](https://www.w3.org/TR/html401/struct/dirlang.html#adef-lang) is about natural language, not programming language, so both approaches are lame in semantic perspective :)

**Comment by mmieluch** [comment]
@zolotov As for the spec: take a closer look ;) `rel` is used always in context of `link` tag, not `style`. `rel` symbolises another file in relation to the current document.

I do agree about `lang` though, it's for natural language... But, since I still believe `rel` is not a part of the spec for `style` tag, it would be a better option.

Semantics aside, would it be a lot of hassle to base the formatting on `lang` -- Seeing as all the other formatting plugins (including this one) already use it? I'm thinking about compatibility here.

**Comment by zolotov** [comment]
@mmieluch you're right, indeed. Anyway both variants have nothing to do with semantics and specs.

I'm not sure that I understood your question about compatibility

**Comment by mmieluch** [comment]
@zolotov I meant it would be the best of both worlds if we could have proper highlighting based on `lang` attribute, because plenty of other plugins, like `vue-syntax-highlight`, are already using it to determine the underlying language within the `script` tag. Would be lovely if Web/PhpStorm could do it too, so we'd be in line with Sublime/Atom users.

**Comment by piotros** [comment]
Agree with @mmieluch.

IMHO there is no need to strictly follow specs delivered by W3C in this case. Top level HTML tags inside Vue components (`template`, `style` and `script`) aren't appended directly into DOM.

In this case we should treat Vue/vue-loader documentations as a main specs for single file vue components.

**Comment by themsaid** [comment]
I end up switching between PHPStorm and sublime in order to work on a laravel/vue project, I hope PHPStorm supports the .vue format soon.

**Comment by MatthewLilley** [comment]
+1

**Comment by mmieluch** [comment]
Thanks @zolotov for implementing the `rel`. You made my PhpSorm usable with Vue again :) Yes, it's a workaround and not fully Vue-compatible solution, but it works and I'm quite happy with it. Of course, it still would be lovely to get the IDE support we discussed earlier <wink wink>.

To sum up for other struggling developers, this how you can currently set up Vue components (I'll use PhpStorm for reference, since this is my platform):

- use [PhpStorm 11 EAP](http://blog.jetbrains.com/phpstorm/) - my current version is 144.4199, I don't know if it worked in earlier versions;
- for ES6 recognition within `script` tag use additional `type="text/babel"` attribute:
```html
<script type="text/babel">
...
</script>
```
- for SASS recognition within `style` tag I use additional `rel="stylesheet/scss" attribue:
    ```html
    <style lang="sass" rel="stylesheet/scss">
    ...
    </style>
    ```

Here's a screenshot with a test component and no errors thrown by the IDE:

![phpstorm-eap-working-vue-component](https://cloud.githubusercontent.com/assets/3188919/13284859/f59a9ed4-daee-11e5-88a6-db75d7fc4efa.png)

Happy coding!

**Comment by mmieluch** [comment]
Dammit, we're almost there... Everything seems to be working fine using the setup above, even in the latest EAP version, EXCEPT... commenting. Right now there's a bug in PhpStorm (I would assume in all IDEA-based products) where it applies HTML-style comments instead of LESS/SASS-style ones.

I [reported a bug](https://youtrack.jetbrains.com/issue/WI-30912), we'll see if and when it gets resolved.

**Comment by chengma** [comment]
*.vue do not support lang='jade', lang='sass' code style auto formate in webstorm

**Comment by se-panfilov** [comment]
Okay, `<style lang="scss" rel="stylesheet/scss" type="text/css">` works fine

But how about **.jade** syntax hightlight?
I mean in templates: `<template lang="jade">`?

**Comment by dddomin3** [comment]
https://youtrack.jetbrains.com/issue/IDEA-106449#tab=Comments

Webstorm doesn't support template language injection... Issue has been up since 2013 with no official word.

**Comment by se-panfilov** [comment]
@dddomin3 Thanks, I've knew it, but hope to find a workaround. 

Btw, did you know, you also can import TypeScript tables for vue:
`Settings(Preferences)` => `Language & Frameworks` =>  `JavaScript` => `Libraries`. Click `Download`, Switch to `TypeScript community stubs`. And download all tabs with vue word.

I'm not sure how it's helps, but anyway it helps for other libs (like chai, etc)

Example: https://youtu.be/4mKiGkokyx8?t=84 (from 1:24)

Besides of all I've shared all the tricks above at stackoverflow: http://stackoverflow.com/questions/36929395/how-to-integrate-webstorm-with-vue-js/36929396#36929396

**Comment by gbhlwm** [comment]
Using `<script lang="babel">` worked for me.

**Comment by Namek** [comment]
Anyone fighting `scss` support, due to close of https://youtrack.jetbrains.com/issue/WEB-14762 this syntax for scss styles worked for me: `<style lang="scss" type="text/scss" scoped></style>` (`scoped` is optional) with latest PhpStorm.

Plus, instead of configuring HTML File Type for `*.vue` I used plugin https://github.com/henjue/vue-for-idea because it seems to recognize *some* directives.

**Comment by iraklisg** [comment]
@Namek I followed the solution you provided. The IDE can succesfully recognize the SCSS syntax without errors BUT now I am not able to build the Vue module using gulp+laravel-elixir-vue-2+laravel-elixir-webpack-official. Please see also this issue here https://github.com/vuejs/laravel-elixir-vue-2/issues/15

**Comment by mmieluch** [comment]
@iraklisg Just use `lang="sass"` like you described in the related issue. Nothing wrong with that. Works for me.

**Comment by iraklisg** [comment]
@mmieluch I do confirm that using `lang="sass"` works fine in terms of compiling the module. 
However, in terms of syntax highlighting, this will not work as expected because the IDE is expecting that we'll use the old _indented_ SASS  syntax and thus it shows synatx errors when using Sassy SCSS syntax. 

PS: I use the PHPSrorm 2016.2.2 IDE with [vue-for-idea](https://github.com/henjue/vue-for-idea) plugin

**Comment by mmieluch** [comment]
@iraklisg Unfortunately the plugin you mention is broken, outdated and removed from the official JetBrains plugins repository. Using it is *NOT* recommended. It's not a problem with this package.

**Comment by mmieluch** [comment]
@iraklisg As a workaround you can use this syntax:

```HTML
<style lang="sass" rel="stylesheet/scss">

</style>
```

See the screenshot: https://github.com/vuejs/vue-syntax-highlight/issues/3#issuecomment-188223377

It's been already mentioned in this issue several times.

**Comment by iraklisg** [comment]
@mmieluch thank you for pointing out this. I open a new issue in the right place this time https://github.com/henjue/vue-for-idea/issues/69

**Comment by asvae** [comment]
Leaving a notice that `rel="stylesheet/scss"` doesn't work for EAP webstorm. Plugin or not won't matter.

Solution wanted. : 3

**Comment by se-panfilov** [comment]
Guys, just FYI:
WebStorm started supporting VueJS officially (from 2017.1 [[blog](https://blog.jetbrains.com/webstorm/2017/02/webstorm-2017-1-eap-171-2822/)])

**Comment by ibufu** [comment]
@se-panfilov, I am using webstorm 2017.1, but it still can't support sass in .vue file.

**Comment by janekkkk** [comment]
@ibufu Try:

`<style lang="scss" rel="stylesheet/scss"></style>`

The lang and rel attributes have to match.

**Comment by piotros** [comment]
@ibufu @janekkkk `rel` attribute is not needed anymore.

**Comment by ibufu** [comment]
```js
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      scss: 'vue-style-loader!css-loader!sass-loader', // <style lang="scss">
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax' // <style lang="sass">
    }
  }
}
```
```<style lang="scss>"```
and make sure Vue.js Templates is associated with *.vue in Editor > File Types. It works for me.

**Comment by RobertDiebels** [comment]
Thought I would leave this here: https://www.jetbrains.com/help/webstorm/2017.1/vue-js.html?search=vue

**Comment by skyronic** [comment]
I believe vue files are now supported in webstorm natively. Closing this issue for now. Thank you.
