### ISSUE TITLE
style lang="scss" incorrectly reporting errors

### ISSUE THREAD

**Issue by endoplasmic** [vuejs/vue-syntax-highlight#52]
![image](https://cloud.githubusercontent.com/assets/118301/15584178/3c0569ee-232e-11e6-9b88-b948e18fe75c.png)

You can see that curly braces and semi colons are showing as errors when they are actually valid.

**Comment by galenyuan** [comment]
same to me, any solution?

**Comment by galenyuan** [comment]
@endoplasmic after installed `sass` in package control, it will be solved.

**Comment by mrliptontea** [comment]
@endoplasmic it depends on which package you use for Sass/SCSS.
I'm using syntax definitions from package [Syntax Highlighting for Sass
](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass) (just `Syntaxes` and `Preferences` folders) because it has much better support than [Sass](https://packagecontrol.io/packages/Sass) (especially for media queries).

This package marks root scope for SCSS as `source.scss`, not `source.sass` as opposed to *Sass* package.

Now if you look into [vue.tmLanguage](https://github.com/vuejs/vue-syntax-highlight/blob/8e729750bc181d3d05d5e74cf7cb8f8c4c19627d/vue.tmLanguage#L430) you'll see for both `sass` and `scss` it will include (line [476](https://github.com/vuejs/vue-syntax-highlight/blob/8e729750bc181d3d05d5e74cf7cb8f8c4c19627d/vue.tmLanguage#L476)) **`source.sass`** syntax.

**The solution**: probably there is no way to keep everyone happy on this, at least not until Sublime will get the official package for Sass/SCSS, which would sort out which way this should be. So temporarily do this:

1. In `Packages/User` create `Vue Syntax Highlight` folder.
2. Copy `vue.tmLanguage` into that folder.
3. Either just change `source.sass` to `source.scss` or duplicate entire `<dict>` tag starting from line 374 and make separate versions for sass and scss by adjusting regex and scope.

Note that if Vue Syntax Highlight package got an update, you would have to repeat this. Otherwise, you will still be using your old override file.

**Comment by endoplasmic** [comment]
@mrliptontea MAAAAAN that was tricky.

1) I had to install the plugin for Sublime 2 (I use Sublime 3) so that I could get the tmLanguage file
2) Now I have 2 listings for "Vue Component" under Syntax, so I just need to remember to pick the first one in the list.

Kind of a ghetto fix, but a fix none the less and I appreciate you taking the time to sort me out :)

**Comment by mrliptontea** [comment]
I just ran into the same issue recently. And yes, it is kind of a ghetto fix :wink:

Ah, you didn't have to install ST2: `.sublime-package` files in `Data/Installed Packages` are basically .zip files - you can unpack them easily. Or just download package source from GitHub.

**Comment by endoplasmic** [comment]
Ahh, nice.

Yah what I ended up doing is removing the Vue Syntax Highlight package, creating the directories that you mentioned above, and changed the line of code you also mentioned above.

Now I've got it all working nicely 👯

**Comment by tandavas** [comment]
@mrliptontea wow! Thank you so much! This method works really well 🎉

**Comment by mismith** [comment]
Another thanks for @mrliptontea! 

Related: I wish there were some instructions for how exactly to get SASS working in .vue files (including Sublime package installs, webpack config, etc). Not necessarily specifics, since those would be tough to maintain, but a general overview like:

1. Install Syntax Highlighting package in your editor
2. `yarn add node-sass sass-loader`
3 etc.

**Comment by mrliptontea** [comment]
Not a problem.

To get started with SCSS and .vue files in Sublime Text, well, install [Vue Syntax Highlight](https://packagecontrol.io/packages/Vue%20Syntax%20Highlight) package.
Apply the modification I explained above, if you use [Syntax Highlighting for Sass](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass).

To use Webpack and compile Sass/SCSS in .vue files use [vue-cli](https://github.com/vuejs/vue-cli) tools with [webpack](https://github.com/vuejs-templates/webpack) or [webpack-simple](https://github.com/vuejs-templates/webpack-simple) template:

```
$ vue init webpack-simple my-project
```

It'll create package.json and webpack config files for you. You might need to modify these config files depending on your project setup.

As of now, only `webpack-simple` comes with Webpack 2 support. But if you want to extract all CSS (from .vue and .scss/.sass files) and bundle them into one .css file, then check out the `webpack` template, namely `build/utils.js`.

**Comment by Doeke** [comment]
Simpler version of @mrliptontea's idea that worked for me (I only ever use scss for my vue files):

1. open `AppData\Roaming\Sublime Text 3\Installed Packages\Vuejs Complete Package.sublime-package` with a zip file manager (I use 7-zip)
2. move the `vue.tmLanguage` file outside the archive and edit it, replacing two occurrences of "sass" with "scss"
3. Close sublime, and drag the file back into the package archive

Easy

**Comment by WangHansen** [comment]
Combine the answer with @Doeke and @mrliptontea 
You can install whatever package you like:

I installed 
1. Sass
2. Syntax Highlighting for Sass
3. Vuejs complete package
4. Vuejs Syntax Highlight

If you installed both 3 and 4, in sublime, you will see two "Vue component" syntax when you click bottom right
So there will be two 'vue.tmLanguage' file under` \Installed Packages\Vuejs Complete Package.sublime-package` and ` \Installed Packages\Vuejs Syntax Highlight.sublime-package`, you can apply fix to either one of them or both by 

> Remove the \<dict\> tag that includes source.sass under \<string\>source.scss.embedded.html\</string\>. 

Or 
>Replace occurrences of "sass" with "scss"

If you only apply fix to one file and it doesn't work, try to switch to another "Vue component" syntax, also you need to restart sublime to make the change

**Comment by petrpacas** [comment]
I'd like to endorse [the way](https://github.com/vuejs/vue-syntax-highlight/issues/52#issuecomment-285162761) @Doeke did it 🎉

**Comment by mismith** [comment]
Because this issue still exists and I keep finding myself searching for how to do it again, here are my exact steps for a new machine, made into as simple a workflow as possible:

1. Install `Vue Syntax Highlight` using the package manager, as normal.
2. Close Sublime.
3. In `~/Library/Application Support/Sublime Text 3/Installed Packages`, extract `Vue Syntax Highlight.sublime-package` using macOS-native `Archive Utility.app`
4. Copy the extracted `Vue Syntax Highlight` folder and its contents into `~/Library/Application Support/Sublime Text 3/Packages/User` (or Dropbox-symlinked equivalent)
5. Do the trick above (remove the `<dict>` entry from `vue.tmLanguage`)
6. Delete `~/Library/Application Support/Sublime Text 3/Installed Packages/Vue Syntax Highlight.sublime-package` (since we now want to use the extracted user version).
7. Re-open Sublime.

**Comment by Celestz** [comment]
I just installed the Sass package for sublime text 3 and it solved my issues, in case anyone else runs into this problem, I was pulling my hairs last week as well.
![image](https://user-images.githubusercontent.com/1031789/33648607-ab6f5608-da95-11e7-97e0-3aa0d68640af.png)

**Comment by lostkeys** [comment]
I just want to add to @Doeke's answer that you can edit the `vue.tmLanguage` file directly in sublime using the [Package Resource Viewer](https://github.com/skuroda/PackageResourceViewer).

**Comment by hotmaycold** [comment]
Combine the answer with @Doeke and @lostkeys
1、command + shift + p  package install  PackageResourceViewer
2、command + shift + p  PackageResourceViewer: Open Resource 打开之前装过的vue高亮文件 Vue Syntax Highlight/vue.tmLanguage 文件
3、将vue.tmLanguage中所有的"sass"替换为"scss"
4、不生效就重启sublime
