### ISSUE TITLE
Incorrect Syntax coloring for @click

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/vue-syntax-highlight#98]
I have tried sort this out, and a theme I know has the settings to make the @click="" inside an html tag color differently, I cannot get it working. Same theme used in different editors has it working.

For Example:
`<button @click="foo">Bar</button>`

Looks like:
<img width="311" alt="screen shot 2017-06-25 at 4 01 06 pm" src="https://user-images.githubusercontent.com/14927668/27520388-98dc5970-59bf-11e7-93ae-721b7c3dce13.png">

When it should look like:
<img width="313" alt="screen shot 2017-06-25 at 4 04 29 pm" src="https://user-images.githubusercontent.com/14927668/27520409-04d4cb76-59c0-11e7-877a-1871a51d7938.png">

**Comment by superjoefly** [comment]
I've had this same issue, but it only occurs in plain .js files. The syntax highlighting works correctly (for me) in .vue files. I'm not sure how to get it to work in plain .js files.

**Comment by ledtorch** [comment]
.vue? But what I need is in .html

**Comment by skyronic** [comment]
Hey @ledtorch the plugin only works for .vue files for now, and I don't think it's possible or advisable to overwrite and extend sublime's default html file syntax highlight at this time.

This only seems to affect event handlers for now. You can optionally consider filing an issue to sublimehq/Packages repo to recognize `@click` as a valid attribute name, since `:click` is valid too.

Another suggestion is opening the file as a "vue component" from sublime's file type selector, even if it's html. Vue component syntax overwrites the default HTML styles so you can get syntax highlight. However you might have to surround your component in `<template>`. Your mileage may vary.

I am closing this issue for now. Thank you!
